/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnniversaryRouteImport } from './routes/anniversary'
import { Route as IndexRouteImport } from './routes/index'

const AnniversaryRoute = AnniversaryRouteImport.update({
  id: '/anniversary',
  path: '/anniversary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anniversary': typeof AnniversaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anniversary': typeof AnniversaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anniversary': typeof AnniversaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anniversary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anniversary'
  id: '__root__' | '/' | '/anniversary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnniversaryRoute: typeof AnniversaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anniversary': {
      id: '/anniversary'
      path: '/anniversary'
      fullPath: '/anniversary'
      preLoaderRoute: typeof AnniversaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnniversaryRoute: AnniversaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
